name: radolan
description: Radar-Online-Aneichung; stuendliche Niederschlagserfassung (17 Wetterradare)
metadata_type: eo

metadata:
    platform:
        code: RADOLAN
    instrument:
        name: RADAR
    product_type: RAD
    format:
        name: NetCDF

measurements:
    - name: 'CC'
      aliases: [cloud_cover]
      dtype: float32
      nodata: .nan
      units: 'eighth'
    - name: 'LWIN'
      aliases: [downward_longwave_radiation]
      dtype: float32
      nodata: .nan
      units: 'W/m^2'
    - name: 'P1m'
      aliases: [precipitation_1m]
      dtype: float32
      nodata: .nan
      units: 'mm'
    - name: 'PA'
      aliases: [atmospheric_pressured]
      dtype: float32
      nodata: .nan
      units: 'hPa'
    - name: 'Prad'
      aliases: [precipitation_RADOLAN]
      dtype: float32
      nodata: .nan
      units: 'mm'
    - name: 'RH'
      aliases: [relative_humidity]
      dtype: float32
      nodata: .nan
      units: '%'
    - name: 'SD'
      aliases: [sunshine_duration]
      dtype: float32
      nodata: .nan
      units: 'h'
    - name: 'SWIN'
      aliases: [downward_shortwave_radiation]
      dtype: float32
      nodata: .nan
      units: 'W/m^2'
    - name: 'TA'
      aliases: [air_temperature_2m]
      dtype: float32
      nodata: .nan
      units: 'Celsius'
    - name: 'WDU'
      aliases: [wind_u_component_eastward]
      dtype: float32
      nodata: .nan
      units: 'm/s'
    - name: 'WDV'
      aliases: [wind_v_component_northward]
      dtype: float32
      nodata: .nan
      units: 'm/s'
    - name: 'WS10m'
      aliases: [wind_speed_10m]
      dtype: float32
      nodata: .nan
      units: 'm/s'