name: nlc_lri_2017_2018_saldi_02
description: 10 Class Land cover Classification (2017/2018)
metadata_type: eo

metadata:
  platform:
    code: LS8
  instrument:
    name: OLI
  product_type: NLC
  format:
    name: GeoTIFF

measurements:
    - name: 'NLC'
      dtype: uint8
      nodata: 0
      units: 'class'
      flags_definition:
        scl:
          bits: [0,1,2,3,4,5,6,7,8,9,10]
          description: Landcover Classes NLC
          values:
            0: Void (no data)
            1: Natural wooded land
            2: Shrubland
            3: Grassland
            4: Waterbodies
            5: Wetlands
            6: Barren land
            7: Cultivated
            8: Build-up
            9: Mines and quarries
            10: Planted Forest